import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script id="react-devtools-semver-patch" strategy="beforeInteractive">
          {`
            (function () {
              if (typeof window === "undefined") return;

              const ensureVersion = (item) => {
                try {
                  if (!item) return;
                  // Handle direct renderer object
                  if (item.version === "" || item.version == null) {
                    item.version = "0.0.0";
                  }
                  // Handle object with renderer property (event payload)
                  if (item.renderer) {
                    if (item.renderer.version === "" || item.renderer.version == null) {
                      item.renderer.version = "0.0.0";
                    }
                  }
                } catch (err) {
                  // ignore
                }
              };

              const patchHook = (hook) => {
                if (!hook || hook.__semverPatched) return;
                hook.__semverPatched = true;

                try {
                  if (hook.renderers && typeof hook.renderers.forEach === "function") {
                    hook.renderers.forEach((renderer) => ensureVersion(renderer));
                  }
                } catch (err) {
                  // ignore
                }

                const originalEmit = hook.emit;
                if (typeof originalEmit === "function") {
                  hook.emit = function () {
                    const args = Array.prototype.slice.call(arguments);
                    if (args[0] === "renderer") {
                      ensureVersion(args[1]);
                    }
                    return originalEmit.apply(this, args);
                  };
                }
              };

              const descriptor = Object.getOwnPropertyDescriptor(window, "__REACT_DEVTOOLS_GLOBAL_HOOK__");

              if (!descriptor || descriptor.configurable !== false) {
                let current = descriptor && descriptor.get ? descriptor.get.call(window) : window.__REACT_DEVTOOLS_GLOBAL_HOOK__;

                Object.defineProperty(window, "__REACT_DEVTOOLS_GLOBAL_HOOK__", {
                  configurable: true,
                  enumerable: descriptor ? descriptor.enumerable : true,
                  get() {
                    return descriptor && descriptor.get ? descriptor.get.call(this) : current;
                  },
                  set(value) {
                    if (descriptor && descriptor.set) {
                      descriptor.set.call(this, value);
                    } else {
                      current = value;
                    }
                    patchHook(value);
                  },
                });

                if (current) {
                  patchHook(current);
                }
              } else if (window.__REACT_DEVTOOLS_GLOBAL_HOOK__) {
                patchHook(window.__REACT_DEVTOOLS_GLOBAL_HOOK__);
              }
            })();
          `}
        </Script>
        {children}
      </body>
    </html>
  );
}
